name:                htest-demo
version:             0.1.0.0
github:              "Jake6329/htest-demo"
license:             BSD3
author:              "Jake Lim"
maintainer:          "jake.lim@me.com"
copyright:           "TODO"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            none

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Jake6329/htest-demo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  htest-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htest-demo

tests:
  htest-demo-test-hunit:
    main:               Spec.hs
    source-dirs:        test/hunit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htest-demo
    - HUnit
  htest-demo-test-qc:
    main:               Spec.hs
    source-dirs:        test/qc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htest-demo
    - QuickCheck
